name: send card

on:
  schedule:
    - cron: '30 23 * * *'
  workflow_dispatch:

jobs:
  send-card:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install fonts
        run: sudo apt-get install -y fonts-wqy-zenhei
      - name: Install dependencies
        run: pip install requests wechatpy pycryptodome pillow
      - name: Run
        env:
          APP_ID: ${{ secrets.APP_ID }}
          APP_SECRET: ${{ secrets.APP_SECRET }}
          TEMPLATE_ID: ${{ secrets.TEMPLATE_ID }}
          WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}
        run: python main.py
